### ISSUE TITLE
Symbolic Toolbox Dependency

### ISSUE THREAD

**Issue by craigim** [libDirectional/libDirectional#5]
The list of requirements only specifies MATLAB r2014a or later and a supported C++ compiler. However, when attempting to compile, I got an error in line 18 of `lib/util/cBinghamNormSymbolic.m`  because it uses a command from the Symbolic Toolbox, which I do not have.

The requirements should either be updated to give a list of required toolboxes, or else the outputs from the symbolic calculations should be included in the project without having to regenerate them on each user's machine.

```
Generate helper functions for d = 2
To use 'sym', the following product must be licensed, installed, and enabled:
  Symbolic Math Toolbox

Error in cBinghamNormSymbolic (line 18)
    X = sym('x', [D, 1]);

Error in generateSymbolic (line 4)
    [c, X] = cBinghamNormSymbolic(D);

Error in compileUtil (line 52)
    generateSymbolic(d);

Error in compileAll (line 16)
compileUtil
```

**Comment by LukasDrude** [comment]
I see, that there is a dependency missing. The symbolic computations are different for each number of dimensions. Would you recommend adding it for a limited number of examples, i.e. `d = 1,...12`?

**Comment by craigim** [comment]
in `lib\util\compileUtil`, the `generateSymbolic` function is called for `d = 2:6`. I haven't gotten as far as using the the library, so I don't know how the symbolic results get used down the road. If the Symbolic Toolbox is only necessary during compile time to generate these files, then I would say to just generate the results as a static file for `d = 2:6` and include that in the repository. If instead the library requires functions that only exist in the Symbolic Toolbox (for instance, the [Riemann Zeta function](https://www.mathworks.com/help/symbolic/zeta.html) does not have a purely numerical analog in the base MATLAB installation), then the project description should be updated to list the Symbolic Toolbox as a prerequisite dependency.

**Comment by LukasDrude** [comment]
Ok, I think I generate the files and add them to the repository. I would then change the lines https://github.com/libDirectional/libDirectional/blob/master/lib/util/compileUtil.m#L50 to only generate more files, if the desired file is missing.

I would like to avoid enforcing the Symbolic Toolbox since most users may not need the normalization constant of the complex Bingham distribution anyway.

**Comment by LukasDrude** [comment]
I now added a pull request for the generated files. Until it is merged, you can take the files from the pull request.

**Comment by gerhardkurz** [comment]
The pull request is merged now. I have also added the recommended toolboxes to the readme file.
